// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaP0hMbjnGoQurACcTZNZ04opRF5mx6Ws',
    appId: '1:372217172098:web:55d947f3e9315432eda49b',
    messagingSenderId: '372217172098',
    projectId: 'breastscan-baf86',
    authDomain: 'breastscan-baf86.firebaseapp.com',
    storageBucket: 'breastscan-baf86.firebasestorage.app',
    measurementId: 'G-KE0JX8WH0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zA4GShf7blz8FHRJlUnJOFuepAkU530',
    appId: '1:372217172098:android:c29c31bec5b943abeda49b',
    messagingSenderId: '372217172098',
    projectId: 'breastscan-baf86',
    storageBucket: 'breastscan-baf86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngwV-LW6mfp-gE5cHCWpckHThYce5sbA',
    appId: '1:372217172098:ios:eebd9ea5541d0fa8eda49b',
    messagingSenderId: '372217172098',
    projectId: 'breastscan-baf86',
    storageBucket: 'breastscan-baf86.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAngwV-LW6mfp-gE5cHCWpckHThYce5sbA',
    appId: '1:372217172098:ios:eebd9ea5541d0fa8eda49b',
    messagingSenderId: '372217172098',
    projectId: 'breastscan-baf86',
    storageBucket: 'breastscan-baf86.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaP0hMbjnGoQurACcTZNZ04opRF5mx6Ws',
    appId: '1:372217172098:web:09dda3c2ad93c015eda49b',
    messagingSenderId: '372217172098',
    projectId: 'breastscan-baf86',
    authDomain: 'breastscan-baf86.firebaseapp.com',
    storageBucket: 'breastscan-baf86.firebasestorage.app',
    measurementId: 'G-8GB8Y1HLK3',
  );

}